### ISSUE TITLE
Error on build/install

### ISSUE THREAD

**Issue by kirkins** [renpytom/rapt-pygame-example#12]
Used the configure command from readme instructions successfully. Now trying to run `android.py --launch build `but failing.

```
[kirkins@philip-pc rapt]$ !516
sudo python2 android.py --launch build ~/code/python/Brain_Music release install

Updating source code.


Updating build files.

Traceback (most recent call last):
  File "android.py", line 69, in <module>
    main()
  File "android.py", line 54, in main
    build.build(iface, args.argument[0], args.argument[1:], launch=args.launch)
  File "buildlib/rapt/build.py", line 498, in build
    "--library", plat.path("extras/google/market_apk_expansion/downloader_library", relative=True),
  File "buildlib/rapt/interface.py", line 238, in call
    subprocess.check_call(args, cwd=plat.RAPT_PATH)
  File "/usr/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by kirkins** [comment]
Should report this in rapt repo instead.
