### ISSUE TITLE
can't build App

### ISSUE THREAD

**Issue by ghost** [renpytom/rapt-pygame-example#13]
Error:
on Pastebin: https://pastebin.com/g75AayHD
or here:

`python android.py build /home/linus/app/USBcontrol/ release

Updating source code.

Updating build files.

Error: Target id 'android-22' is not valid. Use 'android list targets' to get the target ids.
Traceback (most recent call last):
  File "android.py", line 69, in <module>
    main()
  File "android.py", line 54, in main
    build.build(iface, args.argument[0], args.argument[1:], launch=args.launch)
  File "buildlib/rapt/build.py", line 498, in build
    "--library", plat.path("extras/google/market_apk_expansion/downloader_library", relative=True),
  File "buildlib/rapt/interface.py", line 238, in call
    subprocess.check_call(args, cwd=plat.RAPT_PATH)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/linus/RAPT/android-sdk-r24.4.1/tools/android', 'update', 'project', '-p', '.', '-t', 'android-22', '-n', u'USBcontrol-1', '--library', 'extras/google/market_apk_expansion/downloader_library']' returned non-zero exit status 1
`

**Comment by ghost** [comment]
In the newest android sdk, you have to open /RAPT-folder/android-sdk......./tools/android with sudo to download the sdk Platform from android 5.1.1 (API 22) witch is required to compile a pygame with RAPT.
